### PR TITLE
Added "Humidity_Transport" in sensor.py

### PR DESCRIPTION
**Pull request by MaxiKingXXL**
Added "Humidity_Transport" to show "Feuchtetransport" in HA

ABS_HUM_MEASURES = [
    "abs_Humidity_In",
    "abs_Humidity_Out",
    "Humidity_Transport",
]

### CODE REVIEW

**Comment by nielstron** [comment]
Hi @MaxiKingXXL 
I appreciate the request to improve this package! It looks like you created this change through the WebUI of Github - which makes me believe you did not test this change locally to ensure that it will work properly.

Please try this change out in your local home-assistant installation first and report back with the results in your UI and the reported success.

For creating this patch you have already created [a fork of the project](https://github.com/MaxiKingXXL/ha_bayernluefter/tree/patch-1), which you should be able to [add in HACS as custom repository](https://hacs.xyz/docs/faq/custom_repositories/) and load/try the changes in your own setup. Note it might be you need to merge your patch branch (`patch-1`) into `master` in your own fork before the changes take effect.

**Comment by MaxiKingXXL** [comment]
Hi @nielstron 
I have tested this change on my local HA environment already and the correct "Feuchtetransport" value show up properly.
But you are right that the unit is not matching which I overlooked. :)  The Humidity_Transport is in g/24h.
Maybe just GRAMS = "g" as unit would fit better here. 

The is my first change request in github ever and I'm also new in Python. I would be grateful is you could help to with this change.

image
image

**Comment by nielstron** [comment]
That's good to know! To change the unit type, it would be easiest to introduce a new sensor list/map for this class - you see the two lists for abs and rel humidity sensors are grouped together since they share the unit type.

Grams seems unlikely to be the right unit - is it grams/s or grams/24h or something like that? grams would imply it is the accumulated total

**Comment by nielstron** [comment]
Hi @MaxiKingXXL 
I adjusted your PR so that humidity transport should now have the correct unit. Can you please check if it behaves as expected?

**Comment by MaxiKingXXL** [comment]
@nielstron Thanks, for making this change. But for it doesn't show up. Might it be possible that you have nit check in the latest change in sensor.py?

**Comment by nielstron** [comment]
I did not test it yet. I'll try to setup homeassistant with a mock server, then merge into master

**Pull request merged**
